version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole_unbound
    ports:
      - "9711:53/tcp" # DNS tcp
      - "9711:53/udp" # DNS udp
      # - "67:67/udp" # DHCP
      - "9705:80/tcp" # Web interface
    environment:
      TZ: 'America/Recife'
      ADLISTS_URL: 'https://v.firebog.net/hosts/lists.php?type=tick'
      WHITELIST_URL: 'https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt'
      REGEX_BLACKLIST_URL: 'https://raw.githubusercontent.com/mmotti/pihole-regex/master/regex.list'
      WEBPASSWORD: 'senha-aqui'
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
      - './unbound.conf.d:/etc/unbound/unbound.conf.d/'
      # If you need advanced configuration create a mount to access the config file:
      #- './etc-pihole-updatelists/:/etc/pihole-updatelists/'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
